%
%\VignetteIndexEntry{DAFi}
%\VignetteDepends{DAFi}
%\VignetteKeywords{}
%\VignettePackage{DAFi}
%

\documentclass[english]{article}
\usepackage[T1]{fontenc}
\usepackage[latin9]{inputenc}
\usepackage{babel}
<<style-Sweave, eval=TRUE, echo=FALSE, results=tex>>=
BiocStyle::latex()
@ 

\begin{document}
\SweaveOpts{concordance=TRUE}
\begin{center}
\bioctitle[DAFi]{Directed Automated Filtering and 
cluster gating of flow cytometry data}
\par\end{center}{\Large \par}

\begin{center}
Alex Lee, Ivan Chang, and Max Qian
\par\end{center}

\begin{center}
J. Craig Venter Institute
\par\end{center}

\begin{center}
{\footnotesize March, 2017\bigskip{}
\bigskip{}
}
\par\end{center}{\footnotesize \par}

\begin{center}
\textbf{Abstract\bigskip{}
}
\par\end{center}

The DAFi package provides a new framework for cell population identification
for flow cytometry (FCM) data. The framework is compatible with many existing clustering
algorithms such as Kmeans, Kmeans++, mini-batch Kmeans, gaussian mixture models, k-medoids, self-organizing map, etc, 
and allows user to input user defined gating hierarchy to convert the aforementioned unsupervised 
algorithms into powerful semi-supervised and automatic cell population identification approach.
First, the data is read and preprocessed, then configuration files are parsed and implemented as user defined gating directions. 
Clustering algorithm choosen in the initiation is then applied to the data events of the whole FCM data at the start of the iterative
gating/filtering loop, and optionally again at each specified population subset (reclustering). At each gating step, the user can specify
to apply bisecting (events filtering based on user defined boundaries just like in manual gating), slope-based (events filtering based on
user defined slopes), or cluster centroids based filtering (filtering all events members of a cluster based on their centroid's inclusion
or exclusion by the user defined gates). Outputs include population events and percentages table, as well as an events printout table
consisting of all event's transformed channel values and population membership info for external analysis and plotting.
Several built-in plotting options are also available, e.g. 2D dot plots of the user specified gating channels,
and centroids overlay to the 2D dot plots.
\bigskip{}
\bigskip{}

\section{Quick Start}

\Rfunction{DAFi} outputs the population events and percentages tables and additional 2D plots as requested.

library(DAFi)

SampleData <- system.file("extdata", "sample.fcs",package="DAFi")
inclusionConfig <- system.file("extdata", "inclusion.config",package="DAFi")
exclusionConfig <- system.file("extdata", "exclusion.config",package="DAFi")

DAFi(SampleData, inclusionConfig, exclusionConfig, 
		method = "Kmeans",
    clusterSize = 50, initializer = "kmeans++"
		)

DAFi(SampleData, inclusionConfig, exclusionConfig, 
		method = "fSOM",
    xdims = 5, ydims = 5
		)
@


\section{Reading the data}

The DAFi package automatically read in, compensates, transforms and formats the raw FCS data file.

The user just needs to specify the path to the raw FCS file.

\section{Summary}


\end{document}

<<>>=
sessionInfo()
@
