%
%\VignetteIndexEntry{DAFi}
%\VignetteDepends{DAFi}
%\VignetteKeywords{}
%\VignettePackage{DAFi}
%

\documentclass[english]{article}
\usepackage[T1]{fontenc}
\usepackage[latin9]{inputenc}
\usepackage{babel}
<<style-Sweave, eval=TRUE, echo=FALSE, results=tex>>=
#BiocStyle::latex()
@ 

\begin{document}
\SweaveOpts{concordance=TRUE}
\begin{center}
\bioctitle[DAFi]{Directed Automated Filtering and 
cluster gating of flow cytometry data}
\par\end{center}{\Large \par}

\begin{center}
Alex Lee, Ivan Chang, and Max Qian
\par\end{center}

\begin{center}
J. Craig Venter Institute
\par\end{center}

\begin{center}
{\footnotesize March, 2017\bigskip{}
\bigskip{}
}
\par\end{center}{\footnotesize \par}

\begin{center}
\textbf{Abstract\bigskip{}
}
\par\end{center}

The DAFi package provides a new framework for cell population identification
for flow cytometry (FCM) data. The framework is compatible with many existing clustering
algorithms such as Kmeans, Kmeans++, mini-batch Kmeans, gaussian mixture models, k-medoids, self-organizing map, etc, 
and allows user to input user defined gating hierarchy to convert the aforementioned unsupervised 
algorithms into powerful semi-supervised and automatic cell population identification approach.
First, the data is read and preprocessed, then configuration files are parsed and implemented as user defined gating directions. 
Clustering algorithm choosen in the initiation is then applied to the data events of the whole FCM data at the start of the iterative
gating/filtering loop, and optionally again at each specified population subset (reclustering). At each gating step, the user can specify
to apply bisecting (events filtering based on user defined boundaries just like in manual gating), slope-based (events filtering based on
user defined slopes), or cluster centroids based filtering (filtering all events members of a cluster based on their centroid's inclusion
or exclusion by the user defined gates). Outputs include population events and percentages table, as well as an events printout table
consisting of all event's transformed channel values and population membership info for external analysis and plotting.
Several built-in plotting options are also available, e.g. 2D dot plots of the user specified gating channels,
and centroids overlay to the 2D dot plots.
\bigskip{}
\bigskip{}

\section{The easy way}
The easiest way to use this package is using the wrapper function 
\Rfunction{DAFi}. It outputs the population events and percentages tables and additional 2D plots as requested.

<<fig=TRUE>>=
library(DAFi)

SampleData <- system.file("extdata", "sample.fcs",package="DAFi")
inclusionConfig <- system.file("extdata", "inclusion.config",package="DAFi")
exclusionConfig <- system.file("extdata", "exclusion.config",package="DAFi")

DAFi(SampleData, inclusionConfig, exclusionConfig, 
		# select method:
		method = "Kmeans",
                # Kmeans options:
                k = 100, initializer = "kmeans++",
                # FlowSOM options:
                xdims = 10, ydims = 10,
		# output options:
		plotCentroids = TRUE,
		writeOutput = TRUE,
		# experimental excluding gated channels in reclustering
		excludeGated = FALSE
		)
@


\section{Reading the data}

The DAFi package automatically read in, compensates, transforms and formats the raw FCS data file.

The user just needs to specify the path to the raw FCS file.
The data is automatically compensated using \Rcode{\$SPILL} variable from the fcs-file (when \Rcode{compensate} is 
\Rcode{TRUE} but no value is given for \Rcode{spillover}). 
The data can be transformed for specified columns. If no columns are 
provided, all columns from the spillover matrix will be transformed.
Finally, the data can be scaled. By default, it will scale to a mean of zero 
and standard deviation of one. However, specific scaling parameters can be set 
(see the base \R{} \Rfunction{scale} function for more detail).

\medskip{}

\noindent 
<<>>=

# library(DAFi)
# FlowSOM example

# 
# ptm <- proc.time()
# DAFi(SampleData, inclusionConfig, exclusionConfig, xdims=5, ydims=8, method='fSOM', smoothPlot = TRUE)
# proc.time() - ptm
@

\noindent \medskip{}

This function returns a DAFi object, which is actually a \Rclass{list} 
containing several parameters. The data is stored as a matrix in 
\Rcode{\$data}, and all parameter settings to read the data are also stored. 
The begin and end indices of the subsets from the different files can be 
found in \Rcode{\$metadata}.


\section{Summary}

In summary, the DAFi package provides some new ways to look at cytometry
data.
\end{document}

<<>>=
sessionInfo()
@
